function dif(){return mode=='main'?(S.diff||0):0}
function dayNum(){return Math.floor(Date.now()/864e5)}
function wkId(){return Math.floor((Date.now()/864e5+3)/7)}
function pwr(){return HEROES.filter(x=>S.own[x.id]).map(x=>x.dm*mult(x.id)).sort((a,b)=>b-a).slice(0,5).reduce((s,v)=>s+v,0)}
function wbBase(){return Math.max(400,Math.round(2.2*Math.pow(pwr(),1.5)/100)*100)}
function evBase(){return Math.max(150,Math.round(25*Math.pow(pwr(),.6)/10)*10)}
function pickTeam(){const tk=HEROES.filter(x=>x.role=='tank'||x.role=='fighter'),t=[tk[Math.random()*tk.length|0]];while(t.length<5){const x=HEROES[Math.random()*HEROES.length|0];if(!t.includes(x))t.push(x)}return t.map(x=>x.id)}
function genOpps(){S.ar.opp=[.75,.95,1.15].map(f=>({f,t:pickTeam()}))}
function wbCheck(){if(S.wb.wk!=wkId()||!S.wb.base)S.wb={wk:wkId(),dmg:0,claimed:0,tries:0,tday:'',base:wbBase()};if(S.wb.tday!=today()){S.wb.tday=today();S.wb.tries=0}if(S.tw.day!=today())S.tw={day:today(),best:0};if(S.ev.wk!=wkId()||!S.ev.base)S.ev={wk:wkId(),score:0,claimed:0,tries:0,tday:'',base:evBase()};if(S.ev.tday!=today()){S.ev.tday=today();S.ev.tries=0}if(S.ar.tday!=today()){S.ar.tday=today();S.ar.tries=0}if(!S.ar.opp.length)genOpps()}
const TMODS=[['Musuh Gesit','Kecepatan musuh +40%',{spd:1.4}],['Kulit Baja','HP musuh x1,6 tapi serangan x0,8',{hp:1.6,atk:.8}],['Gerombolan','Musuh 1,8x lebih banyak tapi lemah',{cnt:1.8,hp:.7}],['Taring Tajam','Serangan musuh +50%',{atk:1.5}],['Tanpa Penyembuh','Penyembuhan hanya 30%',{heal:.3}],['Elit Semua','Setiap gelombang punya musuh elit',{el:1}]];
const tmod=()=>TMODS[dayNum()%TMODS.length],WBL=['boss','borc','blich','bslime','bspider','bcyc','bghost'],rs=()=>['w','a','x'][Math.random()*3|0];
const TT=[.8,2.4,5,8,12],TIERS=[[0,'100 emas + 1 Esensi'],[0,'300 emas, 2 Esensi, 1 tiket panggil'],[0,'Item Terasah+ dan 4 Esensi'],[0,'Item Mulia+, tiket liontin, 6 Esensi'],[0,'Item Legenda, 2 tiket panggil, 8 Esensi']];
function tthr(i){return Math.round(S.wb.base*TT[i])}
function claimTier(i){if(S.wb.dmg<tthr(i)||((S.wb.claimed>>i)&1))return;S.wb.claimed|=1<<i;if(i==0){S.g+=100;S.es+=1}else if(i==1){S.g+=300;S.es+=2;S.ft++}else if(i==2){S.es+=4;addItem(mkItem(rs(),rollRar([0,70,25,5])))}else if(i==3){S.es+=6;S.fe++;addItem(mkItem(rs(),rollRar([0,0,80,20])))}else{S.es+=8;S.ft+=2;addItem(mkItem(rs(),'SSR'))}sv();sfx('clear');say('Hadiah tier '+(i+1)+' diambil!')}
function newTower(){wbCheck();mode='tower';TM=Object.assign({},tmod()[2]);tutT=99;stage=1;combo=0;lb=0;runG=0;stageG=0;R=TM.el?{el:1}:{};bf={t:0,m:1};P={atk:1,cd:1-.03*S.sh[2],crit:.1+.02*S.sh[1],burn:1,ls:0,as:1};hs=S.deck.map(mkH);layout();startStage()}
function newBoss(){wbCheck();if(S.wb.tries>=3){say('Kesempatan hari ini habis (maks 3)');return}S.wb.tries++;sv();mode='boss';TM={};tutT=99;stage=Math.max(3,Math.floor(best*.8));combo=0;lb=0;runG=0;stageG=0;wbDmg=0;wbT=90;R={};bf={t:0,m:1};P={atk:1,cd:1-.03*S.sh[2],crit:.1+.02*S.sh[1],burn:1,ls:0,as:1};hs=S.deck.map(mkH);layout();startStage()}
function endBoss(){stat('bossRuns');wbLast=Math.floor(wbDmg);S.wb.dmg+=wbLast;sv();st='bossres';sfx('clear');es=[];ps=[];tele=[];sch=[]}
const AR={hp:1.15,atk:1.3},EV={bst:.5,gr:16,nv:28,sp0:2.8,spt:60},ET=[.9,2.7,5.5,9,14],EVT=[['Pesta Slime',['slime','slime','bat']],['Serbuan Goblin',['goblin','gbow','orc']],['Malam Hantu',['ghost','bat','dmage','spider']]];
const ART=[100,250,500,1000,2000],ARR=['150 emas + 1 tiket panggil','400 emas + 2 Esensi','Tiket liontin + item Terasah+','5 Esensi, 2 tiket panggil, item Mulia+','10 Esensi, 3 tiket panggil, item Legenda'],EVR=['150 emas + 2 Esensi','300 emas + 4 Esensi','6 Esensi + tiket liontin','10 Esensi, tiket panggil, item Mulia+','15 Esensi, 2 tiket panggil, item Legenda'];
const rankName=r=>r<100?'Perunggu':r<300?'Perak':r<600?'Emas':r<1000?'Platinum':r<1500?'Berlian':'Legenda',ethr=i=>Math.round(S.ev.base*ET[i]/10)*10;
function wr(s,x,y,n,c,z,a){s=tr(s);let l='',yy=y;s.split(' ').forEach(q=>{if((l+' '+q).length>n){T(l,x,yy,c,z,a);yy+=z+3;l=q}else l=l?l+' '+q:q});T(l,x,yy,c,z,a)}
function giveR(i,tab){const it=(r)=>addItem(mkItem(rs(),r));if(tab=='ar'){if(i==0){S.g+=150;S.ft++}else if(i==1){S.g+=400;S.es+=2}else if(i==2){S.fe++;it(rollRar([0,80,20,0]))}else if(i==3){S.es+=5;S.ft+=2;it(rollRar([0,0,85,15]))}else{S.es+=10;S.ft+=3;it('SSR')}}
else{if(i==0){S.g+=150;S.es+=2}else if(i==1){S.g+=300;S.es+=4}else if(i==2){S.es+=6;S.fe++}else if(i==3){S.es+=10;S.ft++;it(rollRar([0,0,85,15]))}else{S.es+=15;S.ft+=2;it('SSR')}}}
function claimAr(i){if(S.ar.rt<ART[i]||((S.ar.cl>>i)&1))return;S.ar.cl|=1<<i;giveR(i,'ar');sv();sfx('clear');say('Hadiah arena diambil!')}
function claimEv(i){if(S.ev.score<ethr(i)||((S.ev.claimed>>i)&1))return;S.ev.claimed|=1<<i;giveR(i,'ev');sv();sfx('clear');say('Hadiah event diambil!')}
function newArena(i){wbCheck();if(S.ar.tries>=5){say('Kesempatan arena hari ini habis (maks 5)');return}S.ar.tries++;sv();const o=S.ar.opp[i];arI=i;mode='arena';TM={};tutT=99;stage=1;combo=0;lb=0;runG=0;stageG=0;wbT=120;R={};bf={t:0,m:1};P={atk:1,cd:1-.03*S.sh[2],crit:.1+.02*S.sh[1],burn:1,ls:0,as:1};hs=S.deck.map(mkH);layout();
const hm=hs.reduce((s,q)=>s+q.mh/q.d.hp,0)/hs.length,lm=hs.reduce((s,q)=>s+q.lm,0)/hs.length,sk=Math.pow(hs.reduce((s,q)=>s+q.skm,0)/hs.length,1.8);arW=o.t.map((id,k)=>{const d=HEROES[HID[id]];ED['ar'+k]={s:d.s,abs:d.hp*hm*o.f*AR.hp*sk,atk:d.dm*lm*o.f*AR.atk*sk,spd:44,rng:d.melee?26:Math.min(d.rng,170),it:d.it*1.1,sc:3,rangedA:!d.melee,orb:d.ty=='orb'||d.ty=='bolt',oc:EC[d.el]||'#fe8',n:d.n};return'ar'+k});startStage()}
function endArena(win){if(win)stat('arenaWins');const o=S.ar.opp[arI],g0=Math.round(60*o.f),dr=win?Math.round(22*o.f):-14;S.ar.rt=Math.max(0,S.ar.rt+dr);if(win){S.g+=g0;S.ar.w++;if(Math.random()<.15)addItem(mkItem(rs(),rollRar([40,40,16,4])))}else S.ar.l++;arLast={win,dr,g:win?g0:0};stageG=0;S.ar.opp[arI]={f:o.f,t:pickTeam()};sv();st='arenares';sfx(win?'clear':'hurt');es=[];ps=[];tele=[];sch=[]}
function newEvent(){wbCheck();if(S.ev.tries>=3){say('Kesempatan event hari ini habis (maks 3)');return}S.ev.tries++;sv();mode='event';TM={};tutT=99;evKills=0;evT=0;evSp=1;evBaseSt=Math.max(2,Math.floor(best*EV.bst));stage=evBaseSt;combo=0;lb=0;runG=0;stageG=0;wbT=100;R={};bf={t:0,m:1};P={atk:1,cd:1-.03*S.sh[2],crit:.1+.02*S.sh[1],burn:1,ls:0,as:1};hs=S.deck.map(mkH);layout();startStage()}
function endEvent(){stat('events');evLast=evKills*10;S.ev.score+=evLast;stageG=0;sv();st='eventres';sfx('clear');es=[];ps=[];tele=[];sch=[]}
function evTick(dt){evT+=dt;evSp-=dt;if(evSp<=0&&es.length<30){const th=EVT[wkId()%3][1],n=1+Math.floor(evT/EV.nv)+(Math.random()<.3?1:0);for(let i=0;i<n;i++)es.push(spawn(th[Math.random()*th.length|0],660+rnd(0,40),rnd(190,310)));evSp=Math.max(1,EV.sp0-evT/EV.spt);stage=evBaseSt+Math.floor(evT/EV.gr)}}
